fragment SimpleProduct on SimpleProduct {
  price
  rawPrice: price(format: RAW)
  slug
  regularPrice
  rawRegularPrice: regularPrice(format: RAW)
  salePrice
  rawSalePrice: salePrice(format: RAW)
  dateOnSaleTo
  stockStatus
  stockQuantity
  rawDescription: description(format: RAW)
  shortDescription
  averageRating
  weight
  length
  width
  height
  reviewCount
  image {
    sourceUrl
    cartSourceUrl: sourceUrl(size: THUMBNAIL)
    altText
    title
  }
  galleryImages {
    nodes {
      sourceUrl
    }
  }
}
